---
name: Kocom Wallpad with RS485 for 힐스테이트푸르지오수원
version: 2023.08.003
slug: kocom_py
description: Kocom Wallpad for Home Assistant
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
url: https://github.com/vifrost/kocom.py
startup: application
boot: auto
uart: true
map:
  - share:rw
options:
  share/kocom/kocom.conf 설정파일: true
  share/kocom/kocom.py 실행파일: true
schema:
  share/kocom/kocom.conf 설정파일: bool
  share/kocom/kocom.py 실행파일: bool
